In [57]:
#Name: Atharv Gaikwad
#Roll no: 42
#div : A
#Batch:T2A
#Title: 


In [58]:

import numpy as np 

In [59]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])   # Creating the array 
array1    # print the array 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
array1.size     # Find the array size 

9

In [61]:
array1.ndim     # find the N Dimenetion 

2

In [62]:
arr2=np.arange(2,11)    # Arranging the no from 2 to 10 
arr2
b=arr2.reshape(3,3)     # Reshape into the 3 * 3 matrix 
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [63]:
array1.ndim        # find the N Dimenetion 

2

In [64]:
arr3=np.array([1,2,3,4,5,6,7,8,9])
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
arr3[2]    # Find the index 2 

np.int64(3)

In [66]:
arr3[-1]    # find the last Element of the array 

np.int64(9)

In [67]:
array2=np.array([[1,2,3]])
array3=np.array([[5,6,7]])
print(array2)
print(array3)
add= array1+array3           # adding the two array 
print('---------------------')
add

[[1 2 3]]
[[5 6 7]]
---------------------


array([[ 6,  8, 10],
       [ 9, 11, 13],
       [12, 14, 16]])

In [68]:
array12=np.array([[1,2,3],[4,5,6]])
array123=np.array([[5,6,7],[1,2,3]])
print(array2)
print(array3)
sub= array12-array123          # subtract array1 from array2 
print('---------------------')
sub

[[1 2 3]]
[[5 6 7]]
---------------------


array([[-4, -4, -4],
       [ 3,  3,  3]])

In [69]:
array13=np.array([[1,2,3],[4,5,6]])
array123=np.array([[5,6,7],[1,2,3]])
print(array2)
print(array3)
sub= array12**array123        # Square of the array
print('---------------------')
sub

[[1 2 3]]
[[5 6 7]]
---------------------


array([[   1,   64, 2187],
       [   4,   25,  216]])

In [70]:
array12=np.array([[1,2,3],[4,5,6]])
array123=np.array([[5,6,7],[1,2,3]])
print(array2)
print(array3)
sub= array12/array123              # divide the array1 from array2 
print('---------------------')
sub

[[1 2 3]]
[[5 6 7]]
---------------------


array([[0.2       , 0.33333333, 0.42857143],
       [4.        , 2.5       , 2.        ]])

In [71]:
array12=np.array([[1,2,3],[4,5,6]])
array123=np.array([[5,6,7],[1,2,3]])
print(array2)
print(array3)
sub= array12*array123               # multiply array1 frorm array2
print('---------------------')
sub

[[1 2 3]]
[[5 6 7]]
---------------------


array([[ 5, 12, 21],
       [ 4, 10, 18]])

In [75]:
#Self Learning 
array1=np.array([[1,2,3,4,5,6,7,8,9]])  
a=array1.argmax()   #   Return The maximum value index 
print(a)

8


In [76]:
c=array1.argmin()  #   Return the Minimum value index 
print(c)

0


In [79]:
arr = np.array([10, 20, 30, 50])
np.diff(arr)
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])