In [96]:
import numpy as np 

In [97]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
zero_arr= np.zeros(5)
zero_arr

array([0., 0., 0., 0., 0.])

In [99]:
arr2=np.array([[]])

In [100]:
zero_arr.dtype


dtype('float64')

In [101]:
type=zero_arr.astype(int)
type

array([0, 0, 0, 0, 0])

In [102]:
zero_arr.shape

(5,)

In [103]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr2


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [104]:
arr2.dtype


dtype('int64')

In [105]:
arr2.shape

(4, 3)

In [106]:
arr4=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.swapaxes(arr4,1,0)

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [107]:
arr4.max()

np.int64(12)

In [108]:
#arr4.reshape(-1,1)

In [109]:

#arr4=np.linspace(2,6)
#arr4

In [110]:
arr4.sort(axis=0)
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])